### ISSUE TITLE
FFT of IF signals plots and handler

### ISSUE THREAD

**Issue by dudeldeck** [m6c7l/pymmw#9]
Hey,

I have another question regarding the plots.
In the README.md you say, that the 3D-plots are currently not available for IWR1843 ES1.0 and IWR6843 ES2.0.
I use the IWR6843 and therefore as expected do not have these plots.

BUT, I also do not get the FFT of IF signals plots, which I should get?

Do you have any idea what could be the reason of this issue?

Also, I don't quite understand what I need to enter for the handler?

Thank you.

Best regards

**Comment by m6c7l** [comment]
Hi,

FFT of IF does not work with any mmWave SDK demo, and is only available for IWR1443 with a rather old firmware from SDK 1.1.0.2, the so called Capture Demo. Recent hardware revisions need to use the ICBoost or DCA1000 to capture IF data.

In most cases the handler does not need to be specified by the user since pymmw can recognize the handler whenever a standard TI firmware of the SDK or Industrial Toolbox is used.

Best
